### ISSUE TITLE
[CLOSED] Headers in nonstandard directories

### ISSUE THREAD

**Issue by schuhschuh** [cmake-basis/BASIS#339]
<a href="https://github.com/ahundt"><img src="https://avatars.githubusercontent.com/u/55744?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ahundt](https://github.com/ahundt)**
_Wednesday Feb 05, 2014 at 19:19 GMT_
_Originally opened as https://github.com/cmake-basis/legacy/issues/339_

---

If headers are placed in src in a module of a toplevel project, how can we make sure the include paths still work correctly?

I know they will work if the headers are placed in `modulename/include/myheader.hpp` but what if they are in `modulename/src/myheader.hpp`

**Comment by ahundt** [comment]
It seems this problem has come up again with my software installation, some files are missing:
https://github.com/ahundt/grl/issues/128

**Comment by schuhschuh** [comment]
I would say that's by design so. Header files in the `src/` directory are supposed to be private and may not be exposed in your interface (public header files in `include/` directory) of your library.

**Comment by ahundt** [comment]
It is due to my script that unzips and builds a user supplied zip file with source provided by another company (I can't change the contents):
https://github.com/ahundt/grl/blob/master/config/FRI_Client_SDK_Cpp.cmake

I need to install the unzipped headers into an appropriate location so users can include it in their own code.

I think I need to add an `$<INSTALL_INTERFACE:include/mylib>` parameter to the `target_include_directories()` call, but I think I'll also need an installation call for the individual headers.

**Comment by ahundt** [comment]
Or rather, the users don't need to include it, my code includes it so the headers need to be installed and the user's target include paths need to also incorporate those directories.

**Comment by schuhschuh** [comment]
PS: My comment relates to the original issue comment. If it's not about header in `src` vs. `include`, then you are cross-posting about a different issue... ;-)

**Comment by ahundt** [comment]
ah well... this seemed kind of close so didn't want a duplicate... lol can't win. :-)

**Comment by schuhschuh** [comment]
> It seems this problem has come up again

Well, but then this initial comment was misleading... anyway, I'm not sure how I can help there. It appears to have nothing to do with BASIS but the CMake scripts of your project only?

**Comment by ahundt** [comment]
It uses basis calls, moved this to
https://github.com/cmake-basis/BASIS/issues/621
