### ISSUE TITLE
(almost) empty generated basisproject executable

### ISSUE THREAD

**Issue by wittenbe** [cmake-basis/BASIS#598]
I tried following the instructions from the quick start, but I'm having no luck. Turns out that after `make`, the generated basisproject executable is an almost empty python script:

```
#! /usr/bin/python

# ============================================================================
# Copyright (c) 2011-2012 University of Pennsylvania
# Copyright (c) 2013-2016 Andreas Schuh
# All rights reserved.
#
# See COPYING file for license information or visit
# https://cmake-basis.github.io/download.html#license
# ============================================================================

##############################################################################
# @file  basisproject.py
# @brief Project tool used to create and/or modify a BASIS project.
#
# @ingroup Tools
##############################################################################

# ============================================================================
# modules
# ============================================================================

from __future__ import unicode_literals
import sys; import os.path; __dir__ = os.path.dirname(os.path.realpath(__file__)); sys.path.insert(0, os.path.realpath('/home/forte/local/src/BASIS/build/lib/python')); sys.path.insert(0, os.path.realpath('/home/forte/local/src/BASIS/build/lib')) # <-- added by BASIS
```

Let me know if/what additional info you need.

**Comment by wittenbe** [comment]
I only just realized that there's an actual release archive file. That one's generating a proper basisproject executable.

**Comment by schuhschuh** [comment]
Hi, this is a [bug I've just recently introduced](https://github.com/cmake-basis/BASIS/commit/0d2d0aa4c72721f447c43a90202952913976e65a) after the last release. It's been fixed in a downstream project and the fix just needs to be pushed upstream. You could use either the release version, or the master branch before the linked commit.

The mistake in the previous commit is that the following line was not adjusted to account for the modified regular expression:

``` cmake
set (SCRIPT            "${CMAKE_MATCH_3}")
```

must be changed to

``` cmake
set (SCRIPT            "${CMAKE_MATCH_2}")
```
